"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteAccountPayable = exports.registerUpdateAccountPayable = exports.registerInsertAccountPayable = exports.registerGetAccountPayableById = exports.registerGetAccountsPayable = void 0;
var get_accounts_payable_1 = require("./get-accounts-payable");
Object.defineProperty(exports, "registerGetAccountsPayable", { enumerable: true, get: function () { return get_accounts_payable_1.registerGetAccountsPayable; } });
var get_account_payable_by_id_1 = require("./get-account-payable-by-id");
Object.defineProperty(exports, "registerGetAccountPayableById", { enumerable: true, get: function () { return get_account_payable_by_id_1.registerGetAccountPayableById; } });
var insert_account_payable_1 = require("./insert-account-payable");
Object.defineProperty(exports, "registerInsertAccountPayable", { enumerable: true, get: function () { return insert_account_payable_1.registerInsertAccountPayable; } });
var update_account_payable_1 = require("./update-account-payable");
Object.defineProperty(exports, "registerUpdateAccountPayable", { enumerable: true, get: function () { return update_account_payable_1.registerUpdateAccountPayable; } });
var delete_account_payable_1 = require("./delete-account-payable");
Object.defineProperty(exports, "registerDeleteAccountPayable", { enumerable: true, get: function () { return delete_account_payable_1.registerDeleteAccountPayable; } });
