"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteCategory = exports.registerUpdateCategory = exports.registerInsertCategory = exports.registerGetCategoryById = exports.registerGetCategories = void 0;
var get_categories_1 = require("./get-categories");
Object.defineProperty(exports, "registerGetCategories", { enumerable: true, get: function () { return get_categories_1.registerGetCategories; } });
var get_category_by_id_1 = require("./get-category-by-id");
Object.defineProperty(exports, "registerGetCategoryById", { enumerable: true, get: function () { return get_category_by_id_1.registerGetCategoryById; } });
var insert_category_1 = require("./insert-category");
Object.defineProperty(exports, "registerInsertCategory", { enumerable: true, get: function () { return insert_category_1.registerInsertCategory; } });
var update_category_1 = require("./update-category");
Object.defineProperty(exports, "registerUpdateCategory", { enumerable: true, get: function () { return update_category_1.registerUpdateCategory; } });
var delete_category_1 = require("./delete-category");
Object.defineProperty(exports, "registerDeleteCategory", { enumerable: true, get: function () { return delete_category_1.registerDeleteCategory; } });
