"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteAssetTransaction = exports.registerUpdateAssetTransaction = exports.registerInsertAssetTransaction = exports.registerGetAssetTransactionById = exports.registerGetAssetTransactions = void 0;
var get_asset_transactions_1 = require("./get-asset-transactions");
Object.defineProperty(exports, "registerGetAssetTransactions", { enumerable: true, get: function () { return get_asset_transactions_1.registerGetAssetTransactions; } });
var get_asset_transaction_by_id_1 = require("./get-asset-transaction-by-id");
Object.defineProperty(exports, "registerGetAssetTransactionById", { enumerable: true, get: function () { return get_asset_transaction_by_id_1.registerGetAssetTransactionById; } });
var insert_asset_transaction_1 = require("./insert-asset-transaction");
Object.defineProperty(exports, "registerInsertAssetTransaction", { enumerable: true, get: function () { return insert_asset_transaction_1.registerInsertAssetTransaction; } });
var update_asset_transaction_1 = require("./update-asset-transaction");
Object.defineProperty(exports, "registerUpdateAssetTransaction", { enumerable: true, get: function () { return update_asset_transaction_1.registerUpdateAssetTransaction; } });
var delete_asset_transaction_1 = require("./delete-asset-transaction");
Object.defineProperty(exports, "registerDeleteAssetTransaction", { enumerable: true, get: function () { return delete_asset_transaction_1.registerDeleteAssetTransaction; } });
