"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteInvestmentPortfolioAsset = exports.registerUpdateInvestmentPortfolioAsset = exports.registerInsertInvestmentPortfolioAsset = exports.registerGetInvestmentPortfolioAssets = exports.registerDeleteInvestmentPortfolio = exports.registerUpdateInvestmentPortfolio = exports.registerInsertInvestmentPortfolio = exports.registerGetInvestmentPortfolioById = exports.registerGetInvestmentPortfolios = void 0;
var get_investment_portfolios_1 = require("./get-investment-portfolios");
Object.defineProperty(exports, "registerGetInvestmentPortfolios", { enumerable: true, get: function () { return get_investment_portfolios_1.registerGetInvestmentPortfolios; } });
var get_investment_portfolio_by_id_1 = require("./get-investment-portfolio-by-id");
Object.defineProperty(exports, "registerGetInvestmentPortfolioById", { enumerable: true, get: function () { return get_investment_portfolio_by_id_1.registerGetInvestmentPortfolioById; } });
var insert_investment_portfolio_1 = require("./insert-investment-portfolio");
Object.defineProperty(exports, "registerInsertInvestmentPortfolio", { enumerable: true, get: function () { return insert_investment_portfolio_1.registerInsertInvestmentPortfolio; } });
var update_investment_portfolio_1 = require("./update-investment-portfolio");
Object.defineProperty(exports, "registerUpdateInvestmentPortfolio", { enumerable: true, get: function () { return update_investment_portfolio_1.registerUpdateInvestmentPortfolio; } });
var delete_investment_portfolio_1 = require("./delete-investment-portfolio");
Object.defineProperty(exports, "registerDeleteInvestmentPortfolio", { enumerable: true, get: function () { return delete_investment_portfolio_1.registerDeleteInvestmentPortfolio; } });
var get_investment_portfolio_assets_1 = require("./get-investment-portfolio-assets");
Object.defineProperty(exports, "registerGetInvestmentPortfolioAssets", { enumerable: true, get: function () { return get_investment_portfolio_assets_1.registerGetInvestmentPortfolioAssets; } });
var insert_investment_portfolio_asset_1 = require("./insert-investment-portfolio-asset");
Object.defineProperty(exports, "registerInsertInvestmentPortfolioAsset", { enumerable: true, get: function () { return insert_investment_portfolio_asset_1.registerInsertInvestmentPortfolioAsset; } });
var update_investment_portfolio_asset_1 = require("./update-investment-portfolio-asset");
Object.defineProperty(exports, "registerUpdateInvestmentPortfolioAsset", { enumerable: true, get: function () { return update_investment_portfolio_asset_1.registerUpdateInvestmentPortfolioAsset; } });
var delete_investment_portfolio_asset_1 = require("./delete-investment-portfolio-asset");
Object.defineProperty(exports, "registerDeleteInvestmentPortfolioAsset", { enumerable: true, get: function () { return delete_investment_portfolio_asset_1.registerDeleteInvestmentPortfolioAsset; } });
