"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteBudget = exports.registerUpdateBudget = exports.registerInsertBudget = exports.registerGetBudgetById = exports.registerGetBudgets = void 0;
var get_budgets_1 = require("./get-budgets");
Object.defineProperty(exports, "registerGetBudgets", { enumerable: true, get: function () { return get_budgets_1.registerGetBudgets; } });
var get_budget_by_id_1 = require("./get-budget-by-id");
Object.defineProperty(exports, "registerGetBudgetById", { enumerable: true, get: function () { return get_budget_by_id_1.registerGetBudgetById; } });
var insert_budget_1 = require("./insert-budget");
Object.defineProperty(exports, "registerInsertBudget", { enumerable: true, get: function () { return insert_budget_1.registerInsertBudget; } });
var update_budget_1 = require("./update-budget");
Object.defineProperty(exports, "registerUpdateBudget", { enumerable: true, get: function () { return update_budget_1.registerUpdateBudget; } });
var delete_budget_1 = require("./delete-budget");
Object.defineProperty(exports, "registerDeleteBudget", { enumerable: true, get: function () { return delete_budget_1.registerDeleteBudget; } });
