"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerDeleteAccountReceivable = exports.registerUpdateAccountReceivable = exports.registerInsertAccountReceivable = exports.registerGetAccountReceivableById = exports.registerGetAccountsReceivable = void 0;
var get_accounts_receivable_1 = require("./get-accounts-receivable");
Object.defineProperty(exports, "registerGetAccountsReceivable", { enumerable: true, get: function () { return get_accounts_receivable_1.registerGetAccountsReceivable; } });
var get_account_receivable_by_id_1 = require("./get-account-receivable-by-id");
Object.defineProperty(exports, "registerGetAccountReceivableById", { enumerable: true, get: function () { return get_account_receivable_by_id_1.registerGetAccountReceivableById; } });
var insert_account_receivable_1 = require("./insert-account-receivable");
Object.defineProperty(exports, "registerInsertAccountReceivable", { enumerable: true, get: function () { return insert_account_receivable_1.registerInsertAccountReceivable; } });
var update_account_receivable_1 = require("./update-account-receivable");
Object.defineProperty(exports, "registerUpdateAccountReceivable", { enumerable: true, get: function () { return update_account_receivable_1.registerUpdateAccountReceivable; } });
var delete_account_receivable_1 = require("./delete-account-receivable");
Object.defineProperty(exports, "registerDeleteAccountReceivable", { enumerable: true, get: function () { return delete_account_receivable_1.registerDeleteAccountReceivable; } });
